    name: Pylint Check

    on:
      push:
        branches:
          - main
          - master
      pull_request:
        branches:
          - main
          - master

    jobs:
      lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.x' # Specify your Python version
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pylint # Or pip install -r requirements.txt if you have other dependencies
          - name: Run Pylint
            run: pylint your_project_directory/ # Adjust path as needed
